-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Data for table `moddb`.`tag`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO `moddb`.`tag` (assettypeid, tagtypeid, name, text, color, created) VALUES (2, 1, 'v1.17.4', NULL, '#C9C9C9', NULL);
INSERT INTO `moddb`.`tag` (assettypeid, tagtypeid, name, text, color, created) VALUES (2, 1, 'v1.18.1', NULL, '#C9C9C9', NULL);
INSERT INTO `moddb`.`tag` (assettypeid, tagtypeid, name, text, color, created) VALUES (2, 1, 'v1.18.2-rc1', NULL, '#C9C9C9', NULL);

COMMIT;

-- -----------------------------------------------------
-- Data for table `moddb`.`majorversion`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO `moddb`.`majorversion` (majorversionid, name) VALUES (1, '1.17.x');
INSERT INTO `moddb`.`majorversion` (majorversionid, name) VALUES (2, '1.18.x');

COMMIT;


-- -----------------------------------------------------
-- Data for table `moddb`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO `moddb`.`user` (roleid, uid, name, password, email, actiontoken, sessiontoken, sessiontokenvaliduntil, timezone, created, lastmodified, lastonline) VALUES (3, NULL, 'Example User', NULL, 'example.user@example.com', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, NULL);
INSERT INTO `moddb`.`user` (userid, name, created, banneduntil, email) VALUES (2, 'Evil User', NOW(), '9999-12-31', '2+void@localhost');
INSERT INTO `moddb`.`user` (userid, roleid, name, created, email) VALUES (3, 2, 'Moderator User', NOW(), '3+void@localhost');
INSERT INTO `moddb`.`user` (userid, roleid, name, created, email) VALUES (4, 3, 'User 4', NOW(), '4+void@localhost');
INSERT INTO `moddb`.`user` (userid, roleid, name, created, email) VALUES (5, 3, 'User 5', NOW(), '5+void@localhost');
INSERT INTO `moddb`.`user` (userid, roleid, name, created, email) VALUES (6, 3, 'User 6', NOW(), '6+void@localhost');
INSERT INTO `moddb`.`user` (userid, roleid, name, created, email) VALUES (7, 3, 'User 7 __ %_%', NOW(), '7+void@localhost');

COMMIT;


-- -----------------------------------------------------
-- Data for table `moddb`.`mod`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (1, 'examplemodone','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (2, 'examplemodtwo','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (3, 'examplemodthree','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (4, 'examplemodfour','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (5, 'examplemodfive','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (6, 'examplemodsix','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (7, 'examplemodseven','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (8, 'examplemodeight','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (9, 'examplemodnine','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (10, 'examplemodten','Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (11, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (12, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (13, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (14, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (15, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (16, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (17, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (18, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (19, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (20, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (21, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (22, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (23, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (24, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (25, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (26, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (27, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (28, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (29, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (30, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO `moddb`.`mod` (assetid, urlalias, summary, side, created, lastreleased) VALUES (31, NULL, 'Some Summary.', 'both', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

COMMIT;


-- -----------------------------------------------------
-- Data for table `moddb`.`asset`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (2,1,2,1,'Example Mod 1', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 2', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 3 loooonnng name name name name', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 4', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 5', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 6', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 7', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 8', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 9', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 10', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 11', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 12', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 13', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 14', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 15', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 16', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 17', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,1,1,'Example Mod 18', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 19', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 20', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 21', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 22', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 23', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 24', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 25', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 26', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 27', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 28', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 29', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 30', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);
INSERT INTO `moddb`.`asset` (createdbyuserid, editedbyuserid, statusid, assettypeid, name, text, tagscached, created, lastmodified, numsaved) VALUES (1,1,2,1,'Example Mod 31', '<p style="text-align: center;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque leo sem, ultrices vel enim vel, pretium fringilla nisi. Nunc ac massa hendrerit, semper est sed, blandit eros. Sed at placerat lorem, viverra lacinia nibh. Mauris eu nunc a augue rhoncus pharetra ac eu nulla. Fusce elementum sapien sit amet sapien pellentesque, eget porttitor quam eleifend. Maecenas imperdiet justo dolor, id bibendum purus ornare vel. Morbi commodo porttitor nisi, sed finibus eros blandit eget. Nulla quis rhoncus urna.</p>', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1);

COMMIT;

-- -----------------------------------------------------
-- Data for table `moddb`.`moderationrecord`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;
INSERT INTO  `moddb`.`moderationrecord` (targetuserid, kind, until, moderatorid, reason) VALUES (2, 2, '9999-12-31', 3, '');
INSERT INTO  `moddb`.`moderationrecord` (targetuserid, kind, until, moderatorid, reason) VALUES (2, 1, '9999-12-31', 3, 'Comment: bad comment');

COMMIT;

-- -----------------------------------------------------
-- Data for table `moddb`.`comment`
-- -----------------------------------------------------
START TRANSACTION;
USE `moddb`;

INSERT INTO  `moddb`.`comment` (assetid, userid, text, created) VALUES (1, 2, 'normal comment', NOW());
INSERT INTO  `moddb`.`comment` (assetid, userid, text, created) VALUES (1, 2, 'ok comment', NOW());
INSERT INTO  `moddb`.`comment` (assetid, userid, text, created, lastmodaction, deleted) VALUES (1, 2, 'bad comment', NOW(), 1, 1);

COMMIT;
