USE `moddb`;

DELIMITER $$

CREATE OR REPLACE PROCEDURE upgrade_database()
BEGIN

IF NOT EXISTS( (SELECT * FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=(SELECT DATABASE()) AND
 TABLE_NAME='files' AND COLUMN_NAME='order') ) THEN
	ALTER TABLE `files` ADD COLUMN `order` TINYINT NOT NULL DEFAULT 0 AFTER `cdnPath`;
	ALTER TABLE `files` MODIFY COLUMN `order` TINYINT NOT NULL;
END IF;


END $$

CALL upgrade_database() $$

DELIMITER ;
